require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/StringLiterals:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/MultilineBlockChain:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 90
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false
  Max: 15